### ISSUE TITLE
Support OPT-IML model

### ISSUE THREAD

**Issue by ericxsun** [hpcaitech/EnergonAI#184]
Meta has released the [OPT-IML](https://github.com/facebookresearch/metaseq/tree/main/projects/OPT-IML) model (OPT + Instruction Meta-Learning). Could you help me load its checkpoint?

**Comment by binmakeswell** [comment]
Due to limited manpower, it is unrealistic for us to directly provide 1-to-1 example support for all models, but it should be similar to OPT. Thanks.
https://github.com/hpcaitech/EnergonAI/tree/main/examples/opt
