### ISSUE TITLE
Maybe you should add license for using OneFlow's LayerNorm Kernel implement？

### ISSUE THREAD

**Issue by MARD1NO** [hpcaitech/EnergonAI#194]
https://github.com/hpcaitech/EnergonAI/blob/main/energonai/kernel/cuda_native/csrc/one_layer_norm.cuh

Here AITemplate add license for using oneflow's implement
https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/backend/cuda/groupnorm/layer_norm.cuh#L16-L32

**Comment by binmakeswell** [comment]
Thank you for your reminder. Due to the long interval, we need to take some time to check this. If this is true, we will fix it. Thanks.

**Comment by binmakeswell** [comment]
Hi @MARD1NO Thank you for pointing this out. This is a redundant code submitted by a resigned intern and not actually used. We have deleted the relevant code. Sorry for the trouble.
